# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet {
    pname = "NetCoreServer";
    version = "7.0.0";
    sha256 = "0rhc03cm9rq5d0dl5m3m2ia68b4q5bf4vycv5f475dh1as7sh37w";
  })
  (fetchNuGet {
    pname = "NRedisStack";
    version = "0.8.0";
    sha256 = "1y1m7wz2nrjp3pkxdpchrj4lsb03gnvkgx187kl4ndraplw5aijn";
  })
  (fetchNuGet {
    pname = "Pipelines.Sockets.Unofficial";
    version = "2.2.2";
    sha256 = "1irxjvfhl4rm0xqypysfwiwwhaq9vp72560cn4i385yack0c6yrl";
  })
  (fetchNuGet {
    pname = "StackExchange.Redis";
    version = "2.6.96";
    sha256 = "0qa04l26vdjjpxn2infz0z6frkv9d4f9zjmmphwyfy1hj92lm665";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "5.0.1";
    sha256 = "1zvfcd2l1d5qxifsqd0cjyv57nr61a9ac2ca5jinyqmj32wgjd6v";
  })
]
