# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "NetCoreServer"; version = "8.0.7"; sha256 = "171mn5b56ikkjvsx3hvgmh3lga9c2ja31as0hnfr3040rdrj4ij5"; })
  (fetchNuGet { pname = "NetTopologySuite"; version = "2.5.0"; sha256 = "0lzjg7dsfkmxql1ssnyzas98m7wzif11d2ywdr1w0vrhyjny924w"; })
  (fetchNuGet { pname = "NRedisStack"; version = "0.11.0"; sha256 = "0jm6772lngcz0gasai7df46jaxlv13jsrgdimknh2hdrr83hh4sk"; })
  (fetchNuGet { pname = "Pipelines.Sockets.Unofficial"; version = "2.2.8"; sha256 = "0pdhyqfck2s3vf8ksr6yc7sg25rarw830zr0bcx8kq1m0f1sa0p3"; })
  (fetchNuGet { pname = "StackExchange.Redis"; version = "2.6.122"; sha256 = "12hcca53c9mmcdwhl5a63vidaxa673d1cjkhcapw2bjjlvq0r0ih"; })
  (fetchNuGet { pname = "System.IO.Pipelines"; version = "5.0.1"; sha256 = "1zvfcd2l1d5qxifsqd0cjyv57nr61a9ac2ca5jinyqmj32wgjd6v"; })
  (fetchNuGet { pname = "System.Memory"; version = "4.5.4"; sha256 = "14gbbs22mcxwggn0fcfs1b062521azb9fbb7c113x0mq6dzq9h6y"; })
]
